/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Sat Dec 31 2016 20:09:25 GMT+0100 (W. Europe Standard Time)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
"use strict";
exports.ENV = {};
//# sourceMappingURL=env.js.map